Use the product-details declaration as a source of truth for the version & branches
luser/whatthetrain pull request #22
Opened 2017-05-07 12:57 UTC by sylvestre

Closes issue #6

https://product-details.mozilla.org/1.0/firefox_versions.json

2017-05-08 17:40 UTC, luser requested changes
I think you should change this a little bit more--right now the existing code will make one request per branch, which is silly now that all the data comes from the same URL. You should just have it fetch the data once and then loop over branches in the response.

Otherwise this looks good, thanks!

2017-05-08 17:41 UTC, luser commented
The other two changesets look fine. I'm not sure that having the version of ESR.next is super valuable, but once you've removed Aurora it should be fine in terms of information density.

2017-05-08 17:41 UTC, sylvestre commented
Yeah, I have been lazy ;) I will fix that!

2017-05-12 11:54 UTC, sylvestre commented
@luser sorry for the ping. I would like this to land to update moz-corsica! Thanks!

2017-05-12 18:36 UTC, luser commented
FYI we might also need to get https://github.com/luser/whatthetrain/issues/21 fixed to make Corsica happy.

2017-05-12 18:37 UTC, luser commented on trains.js
> +  if (Object.keys(jsonContent).length > 0 && jsonContent.constructor === Object) {
This isn't quite the way I would have written it, but I'll just do a fixup commit after landing this vs. holding your PR up longer.

2017-05-12 18:38 UTC, merged